packageExtensions:
  apollo-link@*:
    dependencies:
      graphql: ^14.6.0
  apollo-http-common@*:
    dependencies:
      graphql: ^14.6.0
  graphql-import-loader@*:
    dependencies:
      graphql: ^14.6.0
  apollo-upload-client@*:
    dependencies:
      graphql: ^14.6.0
  snyk-docker-plugin@*:
    dependencies:
      minimatch: "*"
  snyk-python-plugin@*:
    dependencies:
      tslib: "*"
  "@snyk/composer-lockfile-parser@*":
    dependencies:
      tslib: "*"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
