swagger: "2.0"
info:
  description: "This is the REST API specification for the inventory manager."
  version: "1.0.0"
  title: "Inventory Manager"
  # termsOfService: "http://swagger.io/terms/"
  contact:
    email: "eschablowski"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "{{ host }}"
basePath: "/v1"
schemes:
  - "https"
  - "http"
  - "ws"

tags:
  - GraphQL
  - base

securityDefinitions:
  oauth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  apiKey:
    type: "apiKey"
    name: "apiKey"
    in: "header"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
