---
!import ./openapi3.graphql.yml
---
!import ./openapi3.node.yml
---
!import ./openapi3.search.yml
---
tags:
  - name: Basic
    description: Operations that are not coupled to any Data Source.
  - name: Search
    description: Search operations that can be utilized to generate a list of possible responses.
  - name: GraphQL
    description: Endpoints for the GraphQL server, included to generate a full list of api endpoints.
    externalDocs:
      description: GraphQL Specification
      url: https://graphql.org
